# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('bio', models.CharField(max_length=50)),
                ('des', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('bio', models.CharField(max_length=50)),
                ('des', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('abstract', models.TextField(max_length=100)),
                ('Mno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_no.mno')),
                ('Sep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_no.sep')),
            ],
        ),
    ]
