# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_no', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mno',
            name='des',
        ),
    ]
